# Generated by Django 2.2.8 on 2020-03-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('developer_position', models.CharField(max_length=100)),
                ('introduction_main', models.CharField(max_length=255)),
                ('introduction_typed', models.CharField(max_length=255)),
            ],
        ),
    ]
