# Generated by Django 2.2.8 on 2020-03-08 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0005_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images<function Images.project_name at 0x7f595a0bd400>/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_portfolio.Project')),
            ],
        ),
    ]
