# Generated by Django 2.2.10 on 2020-05-25 11:40

from django.db import migrations, models
import django.db.models.deletion
import my_portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=1500)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('developer_position', models.CharField(max_length=100)),
                ('introduction_main', models.CharField(max_length=255)),
                ('introduction_typed', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(blank=True, upload_to='images/profile')),
                ('about', models.TextField(max_length=1000)),
                ('messages', models.ManyToManyField(blank=True, to='my_portfolio.Contact')),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_summary', models.CharField(max_length=255)),
                ('project_description', models.TextField(max_length=1500)),
                ('github_repo', models.URLField(blank=True)),
                ('live_demo', models.URLField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='my_portfolio.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='my_portfolio.Project')),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=2087)),
                ('icon', models.ImageField(upload_to='images/social')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='my_portfolio.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=my_portfolio.models.content_file_name)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='my_portfolio.Project')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
    ]
