# Generated by Django 2.2.8 on 2020-03-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'about me',
            },
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'home'},
        ),
    ]
