# Generated by Django 2.2.8 on 2020-03-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0004_auto_20200307_1755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
