# Generated by Django 2.2.8 on 2020-03-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0008_socialmediaicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaicon',
            name='link',
            field=models.URLField(max_length=2087),
        ),
    ]
