# Generated by Django 2.2.8 on 2020-03-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0009_auto_20200309_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_repo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live_demo',
            field=models.URLField(blank=True),
        ),
    ]
