# Generated by Django 2.2.10 on 2020-04-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0011_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='about',
            field=models.TextField(default='me', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='messages',
            field=models.ManyToManyField(to='my_portfolio.Contact'),
        ),
        migrations.AddField(
            model_name='person',
            name='projects',
            field=models.ManyToManyField(to='my_portfolio.Project'),
        ),
        migrations.AddField(
            model_name='person',
            name='social',
            field=models.ManyToManyField(to='my_portfolio.SocialMediaIcon'),
        ),
    ]
