# Generated by Django 2.2.10 on 2020-04-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0012_auto_20200425_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='messages',
            field=models.ManyToManyField(blank=True, to='my_portfolio.Contact'),
        ),
        migrations.AlterField(
            model_name='person',
            name='projects',
            field=models.ManyToManyField(blank=True, to='my_portfolio.Project'),
        ),
    ]
