# Generated by Django 2.2.10 on 2020-04-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0013_auto_20200425_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
    ]
