# Generated by Django 2.2.10 on 2020-04-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0014_auto_20200426_1423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
