# Generated by Django 2.2.10 on 2020-04-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0015_delete_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
