# Generated by Django 2.2.10 on 2020-04-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0016_delete_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='social',
            field=models.ManyToManyField(blank=True, to='my_portfolio.SocialMediaIcon'),
        ),
    ]
